/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

function findTheDifference(s, t) {
  let scopy = s.split('').sort();
  let tcopy = t.split('').sort();

  for (let i = 0; i < tcopy.length; i++) {
    if (tcopy[i] !== scopy[i]) {
      return tcopy[i];
    }
  }
}

module.exports = findTheDifference;
